version: '3'
services:
  fluentd:
    build: fluentd
    volumes:
      - nginx-logs:/var/log/nginx/
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: fluentd
      POSTGRES_PASSWORD: fluentd
  nginx-client:
    build: nginx-client
  nginx:
    build: nginx
    volumes:
      - nginx-logs:/var/log/nginx/
  forwarder:
    build: fluent-bit

volumes:
  nginx-logs:
