version: '3'
services:
  fluentd:
    build: fluentd
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: fluentd
      POSTGRES_PASSWORD: fluentd
  nginx-client:
    build: nginx-client
  nginx:
    image: nginx
